language: php

php:
  - 7.2
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --no-dev
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then curl -LSs https://box-project.github.io/box2/installer.php | php; fi

script:
  - phpunit
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php box.phar build; rm -rf vendor; php spress.phar --version; fi

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0957171278778ab21da9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
