build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\spress

environment:
  PHP_CHOCO_VERSION: 5.6.33
  PHP_CACHE_DIR: C:\php

cache:
    - '%PHP_CACHE_DIR% -> appveyor.yml'

init:
    - SET PATH=c:\php;%PATH%
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST %PHP_CACHE_DIR% (SET PHP=0)
    - IF %PHP%==1 cinst php -y --version %PHP_CHOCO_VERSION%  --params "/InstallDir:%PHP_CACHE_DIR%"
    - IF %PHP%==1 cinst composer -y --ia "/DEV=%PHP_CACHE_DIR%"
    - IF %PHP%==1 cinst composer -y --ia "/DEV=%PHP_CACHE_DIR%"
    - IF %PHP%==1 echo @php %%~dp0phpunit.phar %%* > phpunit.bat
    - php -v
    - appveyor DownloadFile https://phar.phpunit.de/phpunit-5.7.phar -FileName phpunit.phar
    - IF %PHP%==1 (composer --version) ELSE (composer self-update)
    - cd %APPVEYOR_BUILD_FOLDER%
    - composer install --no-interaction --no-dev --no-progress --ansi

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - bin\spress.bat --version
    - phpunit
