build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\spress

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"

cache:
    - c:\php -> appveyor.yml

init:
    - SET PATH=c:\php;%PATH%
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile https://windows.php.net/downloads/releases/archives/php-5.6.33-Win32-VC11-x86.zip
    - IF %PHP%==1 7z x php-5.6.33-Win32-VC11-x86.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 echo @php %%~dp0phpunit.phar %%* > phpunit.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo max_execution_time=1200 >> php.ini
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - appveyor DownloadFile https://phar.phpunit.de/phpunit-5.7.phar -FileName phpunit.phar
    - cd c:\projects\spress
    - composer install --no-interaction --no-dev --no-progress --ansi

test_script:
    - cd c:\projects\spress
    - Setlocal EnableDelayedExpansion
    - phpunit
