build: false
shallow_clone: true
clone_folder: c:\projects\spress

environment:
  PHP_CHOCO_VERSION: 7.2.4
  PHP_CACHE_DIR: C:\php

cache:
    - '%PHP_CACHE_DIR% -> appveyor.yml'

init:
    - SET PATH=%PHP_CACHE_DIR%;%PATH%
    - SET PHP=0
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST %PHP_CACHE_DIR% (SET PHP=1)
    - IF %PHP%==0 cinst php -y --version %PHP_CHOCO_VERSION%  --params "/InstallDir:%PHP_CACHE_DIR%"
    - IF %PHP%==0 cinst composer -y --ia "/DEV=%PHP_CACHE_DIR%"
    - php -v
    - IF %PHP%==0 (composer --version) ELSE (composer self-update)
    - cd %APPVEYOR_BUILD_FOLDER%
    - composer install --no-interaction --no-progress

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - vendor\bin\phpunit --colors=always
